# Generated by Django 3.2.12 on 2022-03-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Middle_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
